### ISSUE TITLE
you miss some code？

### ISSUE THREAD

**Issue by chongyangwang-song** [ryanaleksander/softened-similarity-learning#3]
train.py
in loss_fn, line 29
you miss log()?

**Comment by ryanaleksander** [comment]
Thank you for checking out this project. I just checked and you seem to be right.
I'm sorry that things seem to be sloppy, I suddenly became busy in the middle of testing it. I'll update the loss_fn, but I'm afraid I won't be able to test to verify its correctness for the time being.  

Once again, I'm sorry for the inconvenience

**Comment by chongyangwang-song** [comment]
I&nbsp;have&nbsp;modified&nbsp;the&nbsp;code&nbsp;and&nbsp;train&nbsp;the&nbsp;model&nbsp;again，But so far it hasn't&nbsp;gained&nbsp;good&nbsp;performance。I will continue with your work。thanks&nbsp;for&nbsp;your&nbsp;code。in&nbsp;addition，The way you calculate&nbsp;top-1&nbsp;seems&nbsp; not&nbsp;the&nbsp;protocol，&nbsp;but it can be used as a reference。thank&nbsp;you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ryanaleksander/softened-similarity-learning"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月26日(星期四) 下午4:25
收件人:&nbsp;"ryanaleksander/softened-similarity-learning"<softened-similarity-learning@noreply.github.com&gt;;
抄送:&nbsp;"王重阳"<3227303639@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ryanaleksander/softened-similarity-learning] you miss some code？ (#3)





 
Thank you for checking out this project. I just checked and you seem to be right.
 I'm sorry that things seem to be sloppy, I suddenly became busy in the middle of testing it. I'll update the loss_fn, but I'm afraid I won't be able to test to verify its correctness for the time being.
 
Once again, I'm sorry for the inconvenience
